module.exports = 
    nearMeArray =
    [
        {link: '@bakeries', keyWord: 'Bakeries', keyWord1: 'Bakeries'},
        {link: '@bars', keyWord: 'Bars', keyWord1: 'Bar'},
        {link: '@beverage', keyWord: 'Beverage', keyWord1: ''},
        {link: '@bistros', keyWord: 'Bistros', keyWord1: 'Bistro'},
        {link: '@breweries', keyWord: 'Brewery', keyWord1: 'Brewery'},
        {link: '@cafes', keyWord: 'Cafés', keyWord1: 'Café'},
        {link: '@casualDining', keyWord: 'Casual Dining', keyWord1: 'Casual Dining'},
        {link: '@cocktailBars', keyWord: 'Cocktail Bar', keyWord1: 'Cocktail Bar'},
        {link: '@coffeeShops', keyWord: 'Coffee Shops', keyWord1: 'Coffee Shop'},
        {link: '@delis', keyWord: 'Delis', keyWord1: 'Deli'},
        {link: '@dessertShops', keyWord: 'Dessert Shops', keyWord1: 'Dessert Shop'},
        {link: '@diners', keyWord: 'Diners', keyWord1: 'Diner'},
        {link: '@fastCasual', keyWord: 'Fast Casual', keyWord1: 'Fast Casual'},
        {link: '@fastFood', keyWord: 'Fast food', keyWord1: 'Fast Food'},
        {link: '@foodCourts', keyWord: 'Food Courts', keyWord1: 'Food Court'},
        {link: '@foodTrucks', keyWord: 'Food Trucks', keyWord1: 'Food Truck'},
        {link: '@juiceBar', keyWord: 'Juice Bar', keyWord1: 'Juice Bar'},
        {link: '@microbreweries', keyWord: 'Microbreweries', keyWord1: ''},
        {link: '@noodleShops', keyWord: 'Noodle Shops', keyWord1: 'Noodle Shop'},
        {link: '@pizzerias', keyWord: 'Pizzeria', keyWord1: 'Pizzeria'},
        {link: '@pubs', keyWord: 'Pubs', keyWord1: 'Pub'},
        {link: '@quickBites', keyWord: 'Quick Bites', keyWord1: 'Quick Bites'},
        {link: '@sandwichShops', keyWord: 'Sandwich Shops', keyWord1: 'Sandwich Shop'},
        {link: '@taquerias', keyWord: 'Taqueria', keyWord1: 'Taqueria'},
        {link: '@vineyards', keyWord: 'Vineyards', keyWord1: 'Vineyard'},
        {link: '@wineBars', keyWord: 'Wine Bar', keyWord1: 'Wine Bar'},
        {link: '@wineries', keyWord: 'Wineries', keyWord1: ''} 
    ]
